#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EMCCN")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertABS(ABS instance);
    partial void UpdateABS(ABS instance);
    partial void DeleteABS(ABS instance);
    partial void InsertBASE(BASE instance);
    partial void UpdateBASE(BASE instance);
    partial void DeleteBASE(BASE instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WindowsFormsApp1.Properties.Settings.Default.EMCCNConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ABS> ABS
		{
			get
			{
				return this.GetTable<ABS>();
			}
		}
		
		public System.Data.Linq.Table<BASE> BASE
		{
			get
			{
				return this.GetTable<BASE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ABS")]
	public partial class ABS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NOBR;
		
		private System.DateTime _BDATE;
		
		private System.DateTime _EDATE;
		
		private string _BTIME;
		
		private string _ETIME;
		
		private string _H_CODE;
		
		private decimal _TOL_HOURS;
		
		private string _KEY_MAN;
		
		private System.DateTime _KEY_DATE;
		
		private string _YYMM;
		
		private bool _NOTEDIT;
		
		private string _NOTE;
		
		private bool _SYSCREATE;
		
		private decimal _TOL_DAY;
		
		private string _A_NAME;
		
		private string _SERNO;
		
		private System.Nullable<bool> _nocalc;
		
		private System.Nullable<bool> _SYSCREATE1;
		
		private string _Memo;
		
		private string _Guid;
		
		private System.Nullable<decimal> _Balance;
		
		private System.Nullable<decimal> _LeaveHours;
		
		private decimal _OT_HRS;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNOBRChanging(string value);
    partial void OnNOBRChanged();
    partial void OnBDATEChanging(System.DateTime value);
    partial void OnBDATEChanged();
    partial void OnEDATEChanging(System.DateTime value);
    partial void OnEDATEChanged();
    partial void OnBTIMEChanging(string value);
    partial void OnBTIMEChanged();
    partial void OnETIMEChanging(string value);
    partial void OnETIMEChanged();
    partial void OnH_CODEChanging(string value);
    partial void OnH_CODEChanged();
    partial void OnTOL_HOURSChanging(decimal value);
    partial void OnTOL_HOURSChanged();
    partial void OnKEY_MANChanging(string value);
    partial void OnKEY_MANChanged();
    partial void OnKEY_DATEChanging(System.DateTime value);
    partial void OnKEY_DATEChanged();
    partial void OnYYMMChanging(string value);
    partial void OnYYMMChanged();
    partial void OnNOTEDITChanging(bool value);
    partial void OnNOTEDITChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    partial void OnSYSCREATEChanging(bool value);
    partial void OnSYSCREATEChanged();
    partial void OnTOL_DAYChanging(decimal value);
    partial void OnTOL_DAYChanged();
    partial void OnA_NAMEChanging(string value);
    partial void OnA_NAMEChanged();
    partial void OnSERNOChanging(string value);
    partial void OnSERNOChanged();
    partial void OnnocalcChanging(System.Nullable<bool> value);
    partial void OnnocalcChanged();
    partial void OnSYSCREATE1Changing(System.Nullable<bool> value);
    partial void OnSYSCREATE1Changed();
    partial void OnMemoChanging(string value);
    partial void OnMemoChanged();
    partial void OnGuidChanging(string value);
    partial void OnGuidChanged();
    partial void OnBalanceChanging(System.Nullable<decimal> value);
    partial void OnBalanceChanged();
    partial void OnLeaveHoursChanging(System.Nullable<decimal> value);
    partial void OnLeaveHoursChanged();
    partial void OnOT_HRSChanging(decimal value);
    partial void OnOT_HRSChanged();
    #endregion
		
		public ABS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOBR", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NOBR
		{
			get
			{
				return this._NOBR;
			}
			set
			{
				if ((this._NOBR != value))
				{
					this.OnNOBRChanging(value);
					this.SendPropertyChanging();
					this._NOBR = value;
					this.SendPropertyChanged("NOBR");
					this.OnNOBRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BDATE", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime BDATE
		{
			get
			{
				return this._BDATE;
			}
			set
			{
				if ((this._BDATE != value))
				{
					this.OnBDATEChanging(value);
					this.SendPropertyChanging();
					this._BDATE = value;
					this.SendPropertyChanged("BDATE");
					this.OnBDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDATE", DbType="DateTime NOT NULL")]
		public System.DateTime EDATE
		{
			get
			{
				return this._EDATE;
			}
			set
			{
				if ((this._EDATE != value))
				{
					this.OnEDATEChanging(value);
					this.SendPropertyChanging();
					this._EDATE = value;
					this.SendPropertyChanged("EDATE");
					this.OnEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BTIME", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BTIME
		{
			get
			{
				return this._BTIME;
			}
			set
			{
				if ((this._BTIME != value))
				{
					this.OnBTIMEChanging(value);
					this.SendPropertyChanging();
					this._BTIME = value;
					this.SendPropertyChanged("BTIME");
					this.OnBTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETIME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ETIME
		{
			get
			{
				return this._ETIME;
			}
			set
			{
				if ((this._ETIME != value))
				{
					this.OnETIMEChanging(value);
					this.SendPropertyChanging();
					this._ETIME = value;
					this.SendPropertyChanged("ETIME");
					this.OnETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string H_CODE
		{
			get
			{
				return this._H_CODE;
			}
			set
			{
				if ((this._H_CODE != value))
				{
					this.OnH_CODEChanging(value);
					this.SendPropertyChanging();
					this._H_CODE = value;
					this.SendPropertyChanged("H_CODE");
					this.OnH_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOL_HOURS", DbType="Decimal(16,2) NOT NULL")]
		public decimal TOL_HOURS
		{
			get
			{
				return this._TOL_HOURS;
			}
			set
			{
				if ((this._TOL_HOURS != value))
				{
					this.OnTOL_HOURSChanging(value);
					this.SendPropertyChanging();
					this._TOL_HOURS = value;
					this.SendPropertyChanged("TOL_HOURS");
					this.OnTOL_HOURSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this.OnKEY_MANChanging(value);
					this.SendPropertyChanging();
					this._KEY_MAN = value;
					this.SendPropertyChanged("KEY_MAN");
					this.OnKEY_MANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this.OnKEY_DATEChanging(value);
					this.SendPropertyChanging();
					this._KEY_DATE = value;
					this.SendPropertyChanged("KEY_DATE");
					this.OnKEY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YYMM", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string YYMM
		{
			get
			{
				return this._YYMM;
			}
			set
			{
				if ((this._YYMM != value))
				{
					this.OnYYMMChanging(value);
					this.SendPropertyChanging();
					this._YYMM = value;
					this.SendPropertyChanged("YYMM");
					this.OnYYMMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTEDIT", DbType="Bit NOT NULL")]
		public bool NOTEDIT
		{
			get
			{
				return this._NOTEDIT;
			}
			set
			{
				if ((this._NOTEDIT != value))
				{
					this.OnNOTEDITChanging(value);
					this.SendPropertyChanging();
					this._NOTEDIT = value;
					this.SendPropertyChanged("NOTEDIT");
					this.OnNOTEDITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSCREATE", DbType="Bit NOT NULL")]
		public bool SYSCREATE
		{
			get
			{
				return this._SYSCREATE;
			}
			set
			{
				if ((this._SYSCREATE != value))
				{
					this.OnSYSCREATEChanging(value);
					this.SendPropertyChanging();
					this._SYSCREATE = value;
					this.SendPropertyChanged("SYSCREATE");
					this.OnSYSCREATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOL_DAY", DbType="Decimal(16,2) NOT NULL")]
		public decimal TOL_DAY
		{
			get
			{
				return this._TOL_DAY;
			}
			set
			{
				if ((this._TOL_DAY != value))
				{
					this.OnTOL_DAYChanging(value);
					this.SendPropertyChanging();
					this._TOL_DAY = value;
					this.SendPropertyChanged("TOL_DAY");
					this.OnTOL_DAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string A_NAME
		{
			get
			{
				return this._A_NAME;
			}
			set
			{
				if ((this._A_NAME != value))
				{
					this.OnA_NAMEChanging(value);
					this.SendPropertyChanging();
					this._A_NAME = value;
					this.SendPropertyChanged("A_NAME");
					this.OnA_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERNO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SERNO
		{
			get
			{
				return this._SERNO;
			}
			set
			{
				if ((this._SERNO != value))
				{
					this.OnSERNOChanging(value);
					this.SendPropertyChanging();
					this._SERNO = value;
					this.SendPropertyChanged("SERNO");
					this.OnSERNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nocalc", DbType="Bit")]
		public System.Nullable<bool> nocalc
		{
			get
			{
				return this._nocalc;
			}
			set
			{
				if ((this._nocalc != value))
				{
					this.OnnocalcChanging(value);
					this.SendPropertyChanging();
					this._nocalc = value;
					this.SendPropertyChanged("nocalc");
					this.OnnocalcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSCREATE1", DbType="Bit")]
		public System.Nullable<bool> SYSCREATE1
		{
			get
			{
				return this._SYSCREATE1;
			}
			set
			{
				if ((this._SYSCREATE1 != value))
				{
					this.OnSYSCREATE1Changing(value);
					this.SendPropertyChanging();
					this._SYSCREATE1 = value;
					this.SendPropertyChanged("SYSCREATE1");
					this.OnSYSCREATE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memo", DbType="NVarChar(2000)")]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this.OnMemoChanging(value);
					this.SendPropertyChanging();
					this._Memo = value;
					this.SendPropertyChanged("Memo");
					this.OnMemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guid", DbType="NVarChar(50)")]
		public string Guid
		{
			get
			{
				return this._Guid;
			}
			set
			{
				if ((this._Guid != value))
				{
					this.OnGuidChanging(value);
					this.SendPropertyChanging();
					this._Guid = value;
					this.SendPropertyChanged("Guid");
					this.OnGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this.OnBalanceChanging(value);
					this.SendPropertyChanging();
					this._Balance = value;
					this.SendPropertyChanged("Balance");
					this.OnBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaveHours", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> LeaveHours
		{
			get
			{
				return this._LeaveHours;
			}
			set
			{
				if ((this._LeaveHours != value))
				{
					this.OnLeaveHoursChanging(value);
					this.SendPropertyChanging();
					this._LeaveHours = value;
					this.SendPropertyChanged("LeaveHours");
					this.OnLeaveHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OT_HRS", DbType="Decimal(16,2) NOT NULL")]
		public decimal OT_HRS
		{
			get
			{
				return this._OT_HRS;
			}
			set
			{
				if ((this._OT_HRS != value))
				{
					this.OnOT_HRSChanging(value);
					this.SendPropertyChanging();
					this._OT_HRS = value;
					this.SendPropertyChanged("OT_HRS");
					this.OnOT_HRSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BASE")]
	public partial class BASE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NOBR;
		
		private string _NAME_C;
		
		private string _NAME_E;
		
		private string _NAME_P;
		
		private string _SEX;
		
		private System.Nullable<System.DateTime> _BIRDT;
		
		private string _ADDR1;
		
		private string _ADDR2;
		
		private string _TEL1;
		
		private string _TEL2;
		
		private string _BBCALL;
		
		private string _EMAIL;
		
		private string _GSM;
		
		private string _IDNO;
		
		private string _CONT_MAN;
		
		private string _CONT_TEL;
		
		private string _CONT_GSM;
		
		private string _CONT_MAN2;
		
		private string _CONT_TEL2;
		
		private string _CONT_GSM2;
		
		private string _BLOOD;
		
		private string _PASSWORD;
		
		private string _POSTCODE1;
		
		private string _POSTCODE2;
		
		private string _BANK_CODE;
		
		private string _BANKNO;
		
		private string _ACCOUNT_NO;
		
		private string _ACCOUNT_NA;
		
		private string _MARRY;
		
		private string _COUNTRY;
		
		private bool _COUNT_MA;
		
		private string _ARMY;
		
		private string _PRO_MAN1;
		
		private string _PRO_ADDR1;
		
		private string _PRO_ID1;
		
		private string _PRO_TEL1;
		
		private string _PRO_MAN2;
		
		private string _PRO_ADDR2;
		
		private string _PRO_ID2;
		
		private string _PRO_TEL2;
		
		private string _ARMY_TYPE;
		
		private string _N_NOBR;
		
		private string _NOBR_B;
		
		private string _PROVINCE;
		
		private string _BORN_ADDR;
		
		private decimal _TAXCNT;
		
		private string _KEY_MAN;
		
		private System.DateTime _KEY_DATE;
		
		private string _ID_TYPE;
		
		private string _TAXNO;
		
		private decimal _PRETAX;
		
		private string _CONT_REL1;
		
		private string _CONT_REL2;
		
		private string _ACCOUNT_MA;
		
		private string _MATNO;
		
		private string _SUBTEL;
		
		private System.Data.Linq.Binary _PHOTO;
		
		private string _up1_name;
		
		private System.Data.Linq.Binary _up1_file;
		
		private string _up2_name;
		
		private System.Data.Linq.Binary _up2_file;
		
		private string _up3_name;
		
		private System.Data.Linq.Binary _up3_file;
		
		private string _up4_name;
		
		private System.Data.Linq.Binary _up4_file;
		
		private string _up5_name;
		
		private System.Data.Linq.Binary _up5_file;
		
		private string _BASECD;
		
		private string _NAME_AD;
		
		private string _ACCOUNT_US;
		
		private string _ACCOUNT_CN;
		
		private string _NATION;
		
		private string _NHI_ID;
		
		private string _AgentNobr1;
		
		private string _AgentNobr2;
		
		private string _CandidatesWays;
		
		private System.Nullable<System.DateTime> _YearDate;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNOBRChanging(string value);
    partial void OnNOBRChanged();
    partial void OnNAME_CChanging(string value);
    partial void OnNAME_CChanged();
    partial void OnNAME_EChanging(string value);
    partial void OnNAME_EChanged();
    partial void OnNAME_PChanging(string value);
    partial void OnNAME_PChanged();
    partial void OnSEXChanging(string value);
    partial void OnSEXChanged();
    partial void OnBIRDTChanging(System.Nullable<System.DateTime> value);
    partial void OnBIRDTChanged();
    partial void OnADDR1Changing(string value);
    partial void OnADDR1Changed();
    partial void OnADDR2Changing(string value);
    partial void OnADDR2Changed();
    partial void OnTEL1Changing(string value);
    partial void OnTEL1Changed();
    partial void OnTEL2Changing(string value);
    partial void OnTEL2Changed();
    partial void OnBBCALLChanging(string value);
    partial void OnBBCALLChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnGSMChanging(string value);
    partial void OnGSMChanged();
    partial void OnIDNOChanging(string value);
    partial void OnIDNOChanged();
    partial void OnCONT_MANChanging(string value);
    partial void OnCONT_MANChanged();
    partial void OnCONT_TELChanging(string value);
    partial void OnCONT_TELChanged();
    partial void OnCONT_GSMChanging(string value);
    partial void OnCONT_GSMChanged();
    partial void OnCONT_MAN2Changing(string value);
    partial void OnCONT_MAN2Changed();
    partial void OnCONT_TEL2Changing(string value);
    partial void OnCONT_TEL2Changed();
    partial void OnCONT_GSM2Changing(string value);
    partial void OnCONT_GSM2Changed();
    partial void OnBLOODChanging(string value);
    partial void OnBLOODChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnPOSTCODE1Changing(string value);
    partial void OnPOSTCODE1Changed();
    partial void OnPOSTCODE2Changing(string value);
    partial void OnPOSTCODE2Changed();
    partial void OnBANK_CODEChanging(string value);
    partial void OnBANK_CODEChanged();
    partial void OnBANKNOChanging(string value);
    partial void OnBANKNOChanged();
    partial void OnACCOUNT_NOChanging(string value);
    partial void OnACCOUNT_NOChanged();
    partial void OnACCOUNT_NAChanging(string value);
    partial void OnACCOUNT_NAChanged();
    partial void OnMARRYChanging(string value);
    partial void OnMARRYChanged();
    partial void OnCOUNTRYChanging(string value);
    partial void OnCOUNTRYChanged();
    partial void OnCOUNT_MAChanging(bool value);
    partial void OnCOUNT_MAChanged();
    partial void OnARMYChanging(string value);
    partial void OnARMYChanged();
    partial void OnPRO_MAN1Changing(string value);
    partial void OnPRO_MAN1Changed();
    partial void OnPRO_ADDR1Changing(string value);
    partial void OnPRO_ADDR1Changed();
    partial void OnPRO_ID1Changing(string value);
    partial void OnPRO_ID1Changed();
    partial void OnPRO_TEL1Changing(string value);
    partial void OnPRO_TEL1Changed();
    partial void OnPRO_MAN2Changing(string value);
    partial void OnPRO_MAN2Changed();
    partial void OnPRO_ADDR2Changing(string value);
    partial void OnPRO_ADDR2Changed();
    partial void OnPRO_ID2Changing(string value);
    partial void OnPRO_ID2Changed();
    partial void OnPRO_TEL2Changing(string value);
    partial void OnPRO_TEL2Changed();
    partial void OnARMY_TYPEChanging(string value);
    partial void OnARMY_TYPEChanged();
    partial void OnN_NOBRChanging(string value);
    partial void OnN_NOBRChanged();
    partial void OnNOBR_BChanging(string value);
    partial void OnNOBR_BChanged();
    partial void OnPROVINCEChanging(string value);
    partial void OnPROVINCEChanged();
    partial void OnBORN_ADDRChanging(string value);
    partial void OnBORN_ADDRChanged();
    partial void OnTAXCNTChanging(decimal value);
    partial void OnTAXCNTChanged();
    partial void OnKEY_MANChanging(string value);
    partial void OnKEY_MANChanged();
    partial void OnKEY_DATEChanging(System.DateTime value);
    partial void OnKEY_DATEChanged();
    partial void OnID_TYPEChanging(string value);
    partial void OnID_TYPEChanged();
    partial void OnTAXNOChanging(string value);
    partial void OnTAXNOChanged();
    partial void OnPRETAXChanging(decimal value);
    partial void OnPRETAXChanged();
    partial void OnCONT_REL1Changing(string value);
    partial void OnCONT_REL1Changed();
    partial void OnCONT_REL2Changing(string value);
    partial void OnCONT_REL2Changed();
    partial void OnACCOUNT_MAChanging(string value);
    partial void OnACCOUNT_MAChanged();
    partial void OnMATNOChanging(string value);
    partial void OnMATNOChanged();
    partial void OnSUBTELChanging(string value);
    partial void OnSUBTELChanged();
    partial void OnPHOTOChanging(System.Data.Linq.Binary value);
    partial void OnPHOTOChanged();
    partial void Onup1_nameChanging(string value);
    partial void Onup1_nameChanged();
    partial void Onup1_fileChanging(System.Data.Linq.Binary value);
    partial void Onup1_fileChanged();
    partial void Onup2_nameChanging(string value);
    partial void Onup2_nameChanged();
    partial void Onup2_fileChanging(System.Data.Linq.Binary value);
    partial void Onup2_fileChanged();
    partial void Onup3_nameChanging(string value);
    partial void Onup3_nameChanged();
    partial void Onup3_fileChanging(System.Data.Linq.Binary value);
    partial void Onup3_fileChanged();
    partial void Onup4_nameChanging(string value);
    partial void Onup4_nameChanged();
    partial void Onup4_fileChanging(System.Data.Linq.Binary value);
    partial void Onup4_fileChanged();
    partial void Onup5_nameChanging(string value);
    partial void Onup5_nameChanged();
    partial void Onup5_fileChanging(System.Data.Linq.Binary value);
    partial void Onup5_fileChanged();
    partial void OnBASECDChanging(string value);
    partial void OnBASECDChanged();
    partial void OnNAME_ADChanging(string value);
    partial void OnNAME_ADChanged();
    partial void OnACCOUNT_USChanging(string value);
    partial void OnACCOUNT_USChanged();
    partial void OnACCOUNT_CNChanging(string value);
    partial void OnACCOUNT_CNChanged();
    partial void OnNATIONChanging(string value);
    partial void OnNATIONChanged();
    partial void OnNHI_IDChanging(string value);
    partial void OnNHI_IDChanged();
    partial void OnAgentNobr1Changing(string value);
    partial void OnAgentNobr1Changed();
    partial void OnAgentNobr2Changing(string value);
    partial void OnAgentNobr2Changed();
    partial void OnCandidatesWaysChanging(string value);
    partial void OnCandidatesWaysChanged();
    partial void OnYearDateChanging(System.Nullable<System.DateTime> value);
    partial void OnYearDateChanged();
    #endregion
		
		public BASE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOBR", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NOBR
		{
			get
			{
				return this._NOBR;
			}
			set
			{
				if ((this._NOBR != value))
				{
					this.OnNOBRChanging(value);
					this.SendPropertyChanging();
					this._NOBR = value;
					this.SendPropertyChanged("NOBR");
					this.OnNOBRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_C", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME_C
		{
			get
			{
				return this._NAME_C;
			}
			set
			{
				if ((this._NAME_C != value))
				{
					this.OnNAME_CChanging(value);
					this.SendPropertyChanging();
					this._NAME_C = value;
					this.SendPropertyChanged("NAME_C");
					this.OnNAME_CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_E", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME_E
		{
			get
			{
				return this._NAME_E;
			}
			set
			{
				if ((this._NAME_E != value))
				{
					this.OnNAME_EChanging(value);
					this.SendPropertyChanging();
					this._NAME_E = value;
					this.SendPropertyChanged("NAME_E");
					this.OnNAME_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_P", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME_P
		{
			get
			{
				return this._NAME_P;
			}
			set
			{
				if ((this._NAME_P != value))
				{
					this.OnNAME_PChanging(value);
					this.SendPropertyChanging();
					this._NAME_P = value;
					this.SendPropertyChanged("NAME_P");
					this.OnNAME_PChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEX", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SEX
		{
			get
			{
				return this._SEX;
			}
			set
			{
				if ((this._SEX != value))
				{
					this.OnSEXChanging(value);
					this.SendPropertyChanging();
					this._SEX = value;
					this.SendPropertyChanged("SEX");
					this.OnSEXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRDT", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> BIRDT
		{
			get
			{
				return this._BIRDT;
			}
			set
			{
				if ((this._BIRDT != value))
				{
					this.OnBIRDTChanging(value);
					this.SendPropertyChanging();
					this._BIRDT = value;
					this.SendPropertyChanged("BIRDT");
					this.OnBIRDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR1", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string ADDR1
		{
			get
			{
				return this._ADDR1;
			}
			set
			{
				if ((this._ADDR1 != value))
				{
					this.OnADDR1Changing(value);
					this.SendPropertyChanging();
					this._ADDR1 = value;
					this.SendPropertyChanged("ADDR1");
					this.OnADDR1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR2", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string ADDR2
		{
			get
			{
				return this._ADDR2;
			}
			set
			{
				if ((this._ADDR2 != value))
				{
					this.OnADDR2Changing(value);
					this.SendPropertyChanging();
					this._ADDR2 = value;
					this.SendPropertyChanged("ADDR2");
					this.OnADDR2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEL1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TEL1
		{
			get
			{
				return this._TEL1;
			}
			set
			{
				if ((this._TEL1 != value))
				{
					this.OnTEL1Changing(value);
					this.SendPropertyChanging();
					this._TEL1 = value;
					this.SendPropertyChanged("TEL1");
					this.OnTEL1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEL2", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TEL2
		{
			get
			{
				return this._TEL2;
			}
			set
			{
				if ((this._TEL2 != value))
				{
					this.OnTEL2Changing(value);
					this.SendPropertyChanging();
					this._TEL2 = value;
					this.SendPropertyChanged("TEL2");
					this.OnTEL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BBCALL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BBCALL
		{
			get
			{
				return this._BBCALL;
			}
			set
			{
				if ((this._BBCALL != value))
				{
					this.OnBBCALLChanging(value);
					this.SendPropertyChanging();
					this._BBCALL = value;
					this.SendPropertyChanged("BBCALL");
					this.OnBBCALLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSM", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GSM
		{
			get
			{
				return this._GSM;
			}
			set
			{
				if ((this._GSM != value))
				{
					this.OnGSMChanging(value);
					this.SendPropertyChanging();
					this._GSM = value;
					this.SendPropertyChanged("GSM");
					this.OnGSMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string IDNO
		{
			get
			{
				return this._IDNO;
			}
			set
			{
				if ((this._IDNO != value))
				{
					this.OnIDNOChanging(value);
					this.SendPropertyChanging();
					this._IDNO = value;
					this.SendPropertyChanged("IDNO");
					this.OnIDNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_MAN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CONT_MAN
		{
			get
			{
				return this._CONT_MAN;
			}
			set
			{
				if ((this._CONT_MAN != value))
				{
					this.OnCONT_MANChanging(value);
					this.SendPropertyChanging();
					this._CONT_MAN = value;
					this.SendPropertyChanged("CONT_MAN");
					this.OnCONT_MANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_TEL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CONT_TEL
		{
			get
			{
				return this._CONT_TEL;
			}
			set
			{
				if ((this._CONT_TEL != value))
				{
					this.OnCONT_TELChanging(value);
					this.SendPropertyChanging();
					this._CONT_TEL = value;
					this.SendPropertyChanged("CONT_TEL");
					this.OnCONT_TELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_GSM", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CONT_GSM
		{
			get
			{
				return this._CONT_GSM;
			}
			set
			{
				if ((this._CONT_GSM != value))
				{
					this.OnCONT_GSMChanging(value);
					this.SendPropertyChanging();
					this._CONT_GSM = value;
					this.SendPropertyChanged("CONT_GSM");
					this.OnCONT_GSMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_MAN2", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CONT_MAN2
		{
			get
			{
				return this._CONT_MAN2;
			}
			set
			{
				if ((this._CONT_MAN2 != value))
				{
					this.OnCONT_MAN2Changing(value);
					this.SendPropertyChanging();
					this._CONT_MAN2 = value;
					this.SendPropertyChanged("CONT_MAN2");
					this.OnCONT_MAN2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_TEL2", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CONT_TEL2
		{
			get
			{
				return this._CONT_TEL2;
			}
			set
			{
				if ((this._CONT_TEL2 != value))
				{
					this.OnCONT_TEL2Changing(value);
					this.SendPropertyChanging();
					this._CONT_TEL2 = value;
					this.SendPropertyChanged("CONT_TEL2");
					this.OnCONT_TEL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_GSM2", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CONT_GSM2
		{
			get
			{
				return this._CONT_GSM2;
			}
			set
			{
				if ((this._CONT_GSM2 != value))
				{
					this.OnCONT_GSM2Changing(value);
					this.SendPropertyChanging();
					this._CONT_GSM2 = value;
					this.SendPropertyChanged("CONT_GSM2");
					this.OnCONT_GSM2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOOD", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BLOOD
		{
			get
			{
				return this._BLOOD;
			}
			set
			{
				if ((this._BLOOD != value))
				{
					this.OnBLOODChanging(value);
					this.SendPropertyChanging();
					this._BLOOD = value;
					this.SendPropertyChanged("BLOOD");
					this.OnBLOODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTCODE1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string POSTCODE1
		{
			get
			{
				return this._POSTCODE1;
			}
			set
			{
				if ((this._POSTCODE1 != value))
				{
					this.OnPOSTCODE1Changing(value);
					this.SendPropertyChanging();
					this._POSTCODE1 = value;
					this.SendPropertyChanged("POSTCODE1");
					this.OnPOSTCODE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTCODE2", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string POSTCODE2
		{
			get
			{
				return this._POSTCODE2;
			}
			set
			{
				if ((this._POSTCODE2 != value))
				{
					this.OnPOSTCODE2Changing(value);
					this.SendPropertyChanging();
					this._POSTCODE2 = value;
					this.SendPropertyChanged("POSTCODE2");
					this.OnPOSTCODE2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANK_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BANK_CODE
		{
			get
			{
				return this._BANK_CODE;
			}
			set
			{
				if ((this._BANK_CODE != value))
				{
					this.OnBANK_CODEChanging(value);
					this.SendPropertyChanging();
					this._BANK_CODE = value;
					this.SendPropertyChanged("BANK_CODE");
					this.OnBANK_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKNO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BANKNO
		{
			get
			{
				return this._BANKNO;
			}
			set
			{
				if ((this._BANKNO != value))
				{
					this.OnBANKNOChanging(value);
					this.SendPropertyChanging();
					this._BANKNO = value;
					this.SendPropertyChanged("BANKNO");
					this.OnBANKNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ACCOUNT_NO
		{
			get
			{
				return this._ACCOUNT_NO;
			}
			set
			{
				if ((this._ACCOUNT_NO != value))
				{
					this.OnACCOUNT_NOChanging(value);
					this.SendPropertyChanging();
					this._ACCOUNT_NO = value;
					this.SendPropertyChanged("ACCOUNT_NO");
					this.OnACCOUNT_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_NA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ACCOUNT_NA
		{
			get
			{
				return this._ACCOUNT_NA;
			}
			set
			{
				if ((this._ACCOUNT_NA != value))
				{
					this.OnACCOUNT_NAChanging(value);
					this.SendPropertyChanging();
					this._ACCOUNT_NA = value;
					this.SendPropertyChanged("ACCOUNT_NA");
					this.OnACCOUNT_NAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARRY", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MARRY
		{
			get
			{
				return this._MARRY;
			}
			set
			{
				if ((this._MARRY != value))
				{
					this.OnMARRYChanging(value);
					this.SendPropertyChanging();
					this._MARRY = value;
					this.SendPropertyChanged("MARRY");
					this.OnMARRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string COUNTRY
		{
			get
			{
				return this._COUNTRY;
			}
			set
			{
				if ((this._COUNTRY != value))
				{
					this.OnCOUNTRYChanging(value);
					this.SendPropertyChanging();
					this._COUNTRY = value;
					this.SendPropertyChanged("COUNTRY");
					this.OnCOUNTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNT_MA", DbType="Bit NOT NULL")]
		public bool COUNT_MA
		{
			get
			{
				return this._COUNT_MA;
			}
			set
			{
				if ((this._COUNT_MA != value))
				{
					this.OnCOUNT_MAChanging(value);
					this.SendPropertyChanging();
					this._COUNT_MA = value;
					this.SendPropertyChanged("COUNT_MA");
					this.OnCOUNT_MAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARMY", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ARMY
		{
			get
			{
				return this._ARMY;
			}
			set
			{
				if ((this._ARMY != value))
				{
					this.OnARMYChanging(value);
					this.SendPropertyChanging();
					this._ARMY = value;
					this.SendPropertyChanged("ARMY");
					this.OnARMYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_MAN1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PRO_MAN1
		{
			get
			{
				return this._PRO_MAN1;
			}
			set
			{
				if ((this._PRO_MAN1 != value))
				{
					this.OnPRO_MAN1Changing(value);
					this.SendPropertyChanging();
					this._PRO_MAN1 = value;
					this.SendPropertyChanged("PRO_MAN1");
					this.OnPRO_MAN1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_ADDR1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PRO_ADDR1
		{
			get
			{
				return this._PRO_ADDR1;
			}
			set
			{
				if ((this._PRO_ADDR1 != value))
				{
					this.OnPRO_ADDR1Changing(value);
					this.SendPropertyChanging();
					this._PRO_ADDR1 = value;
					this.SendPropertyChanged("PRO_ADDR1");
					this.OnPRO_ADDR1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_ID1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PRO_ID1
		{
			get
			{
				return this._PRO_ID1;
			}
			set
			{
				if ((this._PRO_ID1 != value))
				{
					this.OnPRO_ID1Changing(value);
					this.SendPropertyChanging();
					this._PRO_ID1 = value;
					this.SendPropertyChanged("PRO_ID1");
					this.OnPRO_ID1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_TEL1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PRO_TEL1
		{
			get
			{
				return this._PRO_TEL1;
			}
			set
			{
				if ((this._PRO_TEL1 != value))
				{
					this.OnPRO_TEL1Changing(value);
					this.SendPropertyChanging();
					this._PRO_TEL1 = value;
					this.SendPropertyChanged("PRO_TEL1");
					this.OnPRO_TEL1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_MAN2", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PRO_MAN2
		{
			get
			{
				return this._PRO_MAN2;
			}
			set
			{
				if ((this._PRO_MAN2 != value))
				{
					this.OnPRO_MAN2Changing(value);
					this.SendPropertyChanging();
					this._PRO_MAN2 = value;
					this.SendPropertyChanged("PRO_MAN2");
					this.OnPRO_MAN2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_ADDR2", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PRO_ADDR2
		{
			get
			{
				return this._PRO_ADDR2;
			}
			set
			{
				if ((this._PRO_ADDR2 != value))
				{
					this.OnPRO_ADDR2Changing(value);
					this.SendPropertyChanging();
					this._PRO_ADDR2 = value;
					this.SendPropertyChanged("PRO_ADDR2");
					this.OnPRO_ADDR2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_ID2", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PRO_ID2
		{
			get
			{
				return this._PRO_ID2;
			}
			set
			{
				if ((this._PRO_ID2 != value))
				{
					this.OnPRO_ID2Changing(value);
					this.SendPropertyChanging();
					this._PRO_ID2 = value;
					this.SendPropertyChanged("PRO_ID2");
					this.OnPRO_ID2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_TEL2", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PRO_TEL2
		{
			get
			{
				return this._PRO_TEL2;
			}
			set
			{
				if ((this._PRO_TEL2 != value))
				{
					this.OnPRO_TEL2Changing(value);
					this.SendPropertyChanging();
					this._PRO_TEL2 = value;
					this.SendPropertyChanged("PRO_TEL2");
					this.OnPRO_TEL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARMY_TYPE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ARMY_TYPE
		{
			get
			{
				return this._ARMY_TYPE;
			}
			set
			{
				if ((this._ARMY_TYPE != value))
				{
					this.OnARMY_TYPEChanging(value);
					this.SendPropertyChanging();
					this._ARMY_TYPE = value;
					this.SendPropertyChanged("ARMY_TYPE");
					this.OnARMY_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_NOBR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string N_NOBR
		{
			get
			{
				return this._N_NOBR;
			}
			set
			{
				if ((this._N_NOBR != value))
				{
					this.OnN_NOBRChanging(value);
					this.SendPropertyChanging();
					this._N_NOBR = value;
					this.SendPropertyChanged("N_NOBR");
					this.OnN_NOBRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOBR_B", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOBR_B
		{
			get
			{
				return this._NOBR_B;
			}
			set
			{
				if ((this._NOBR_B != value))
				{
					this.OnNOBR_BChanging(value);
					this.SendPropertyChanging();
					this._NOBR_B = value;
					this.SendPropertyChanged("NOBR_B");
					this.OnNOBR_BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVINCE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PROVINCE
		{
			get
			{
				return this._PROVINCE;
			}
			set
			{
				if ((this._PROVINCE != value))
				{
					this.OnPROVINCEChanging(value);
					this.SendPropertyChanging();
					this._PROVINCE = value;
					this.SendPropertyChanged("PROVINCE");
					this.OnPROVINCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BORN_ADDR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BORN_ADDR
		{
			get
			{
				return this._BORN_ADDR;
			}
			set
			{
				if ((this._BORN_ADDR != value))
				{
					this.OnBORN_ADDRChanging(value);
					this.SendPropertyChanging();
					this._BORN_ADDR = value;
					this.SendPropertyChanged("BORN_ADDR");
					this.OnBORN_ADDRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXCNT", DbType="Decimal(16,2) NOT NULL")]
		public decimal TAXCNT
		{
			get
			{
				return this._TAXCNT;
			}
			set
			{
				if ((this._TAXCNT != value))
				{
					this.OnTAXCNTChanging(value);
					this.SendPropertyChanging();
					this._TAXCNT = value;
					this.SendPropertyChanged("TAXCNT");
					this.OnTAXCNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this.OnKEY_MANChanging(value);
					this.SendPropertyChanging();
					this._KEY_MAN = value;
					this.SendPropertyChanged("KEY_MAN");
					this.OnKEY_MANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this.OnKEY_DATEChanging(value);
					this.SendPropertyChanging();
					this._KEY_DATE = value;
					this.SendPropertyChanged("KEY_DATE");
					this.OnKEY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TYPE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ID_TYPE
		{
			get
			{
				return this._ID_TYPE;
			}
			set
			{
				if ((this._ID_TYPE != value))
				{
					this.OnID_TYPEChanging(value);
					this.SendPropertyChanging();
					this._ID_TYPE = value;
					this.SendPropertyChanged("ID_TYPE");
					this.OnID_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXNO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TAXNO
		{
			get
			{
				return this._TAXNO;
			}
			set
			{
				if ((this._TAXNO != value))
				{
					this.OnTAXNOChanging(value);
					this.SendPropertyChanging();
					this._TAXNO = value;
					this.SendPropertyChanged("TAXNO");
					this.OnTAXNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRETAX", DbType="Decimal(16,2) NOT NULL")]
		public decimal PRETAX
		{
			get
			{
				return this._PRETAX;
			}
			set
			{
				if ((this._PRETAX != value))
				{
					this.OnPRETAXChanging(value);
					this.SendPropertyChanging();
					this._PRETAX = value;
					this.SendPropertyChanged("PRETAX");
					this.OnPRETAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_REL1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CONT_REL1
		{
			get
			{
				return this._CONT_REL1;
			}
			set
			{
				if ((this._CONT_REL1 != value))
				{
					this.OnCONT_REL1Changing(value);
					this.SendPropertyChanging();
					this._CONT_REL1 = value;
					this.SendPropertyChanged("CONT_REL1");
					this.OnCONT_REL1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_REL2", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CONT_REL2
		{
			get
			{
				return this._CONT_REL2;
			}
			set
			{
				if ((this._CONT_REL2 != value))
				{
					this.OnCONT_REL2Changing(value);
					this.SendPropertyChanging();
					this._CONT_REL2 = value;
					this.SendPropertyChanged("CONT_REL2");
					this.OnCONT_REL2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_MA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ACCOUNT_MA
		{
			get
			{
				return this._ACCOUNT_MA;
			}
			set
			{
				if ((this._ACCOUNT_MA != value))
				{
					this.OnACCOUNT_MAChanging(value);
					this.SendPropertyChanging();
					this._ACCOUNT_MA = value;
					this.SendPropertyChanged("ACCOUNT_MA");
					this.OnACCOUNT_MAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATNO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MATNO
		{
			get
			{
				return this._MATNO;
			}
			set
			{
				if ((this._MATNO != value))
				{
					this.OnMATNOChanging(value);
					this.SendPropertyChanging();
					this._MATNO = value;
					this.SendPropertyChanged("MATNO");
					this.OnMATNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTEL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SUBTEL
		{
			get
			{
				return this._SUBTEL;
			}
			set
			{
				if ((this._SUBTEL != value))
				{
					this.OnSUBTELChanging(value);
					this.SendPropertyChanging();
					this._SUBTEL = value;
					this.SendPropertyChanged("SUBTEL");
					this.OnSUBTELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHOTO", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PHOTO
		{
			get
			{
				return this._PHOTO;
			}
			set
			{
				if ((this._PHOTO != value))
				{
					this.OnPHOTOChanging(value);
					this.SendPropertyChanging();
					this._PHOTO = value;
					this.SendPropertyChanged("PHOTO");
					this.OnPHOTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_up1_name", DbType="NVarChar(50)")]
		public string up1_name
		{
			get
			{
				return this._up1_name;
			}
			set
			{
				if ((this._up1_name != value))
				{
					this.Onup1_nameChanging(value);
					this.SendPropertyChanging();
					this._up1_name = value;
					this.SendPropertyChanged("up1_name");
					this.Onup1_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_up1_file", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary up1_file
		{
			get
			{
				return this._up1_file;
			}
			set
			{
				if ((this._up1_file != value))
				{
					this.Onup1_fileChanging(value);
					this.SendPropertyChanging();
					this._up1_file = value;
					this.SendPropertyChanged("up1_file");
					this.Onup1_fileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_up2_name", DbType="NVarChar(50)")]
		public string up2_name
		{
			get
			{
				return this._up2_name;
			}
			set
			{
				if ((this._up2_name != value))
				{
					this.Onup2_nameChanging(value);
					this.SendPropertyChanging();
					this._up2_name = value;
					this.SendPropertyChanged("up2_name");
					this.Onup2_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_up2_file", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary up2_file
		{
			get
			{
				return this._up2_file;
			}
			set
			{
				if ((this._up2_file != value))
				{
					this.Onup2_fileChanging(value);
					this.SendPropertyChanging();
					this._up2_file = value;
					this.SendPropertyChanged("up2_file");
					this.Onup2_fileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_up3_name", DbType="NVarChar(50)")]
		public string up3_name
		{
			get
			{
				return this._up3_name;
			}
			set
			{
				if ((this._up3_name != value))
				{
					this.Onup3_nameChanging(value);
					this.SendPropertyChanging();
					this._up3_name = value;
					this.SendPropertyChanged("up3_name");
					this.Onup3_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_up3_file", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary up3_file
		{
			get
			{
				return this._up3_file;
			}
			set
			{
				if ((this._up3_file != value))
				{
					this.Onup3_fileChanging(value);
					this.SendPropertyChanging();
					this._up3_file = value;
					this.SendPropertyChanged("up3_file");
					this.Onup3_fileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_up4_name", DbType="NVarChar(50)")]
		public string up4_name
		{
			get
			{
				return this._up4_name;
			}
			set
			{
				if ((this._up4_name != value))
				{
					this.Onup4_nameChanging(value);
					this.SendPropertyChanging();
					this._up4_name = value;
					this.SendPropertyChanged("up4_name");
					this.Onup4_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_up4_file", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary up4_file
		{
			get
			{
				return this._up4_file;
			}
			set
			{
				if ((this._up4_file != value))
				{
					this.Onup4_fileChanging(value);
					this.SendPropertyChanging();
					this._up4_file = value;
					this.SendPropertyChanged("up4_file");
					this.Onup4_fileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_up5_name", DbType="NVarChar(50)")]
		public string up5_name
		{
			get
			{
				return this._up5_name;
			}
			set
			{
				if ((this._up5_name != value))
				{
					this.Onup5_nameChanging(value);
					this.SendPropertyChanging();
					this._up5_name = value;
					this.SendPropertyChanged("up5_name");
					this.Onup5_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_up5_file", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary up5_file
		{
			get
			{
				return this._up5_file;
			}
			set
			{
				if ((this._up5_file != value))
				{
					this.Onup5_fileChanging(value);
					this.SendPropertyChanging();
					this._up5_file = value;
					this.SendPropertyChanged("up5_file");
					this.Onup5_fileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BASECD", DbType="NVarChar(50)")]
		public string BASECD
		{
			get
			{
				return this._BASECD;
			}
			set
			{
				if ((this._BASECD != value))
				{
					this.OnBASECDChanging(value);
					this.SendPropertyChanging();
					this._BASECD = value;
					this.SendPropertyChanged("BASECD");
					this.OnBASECDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_AD", DbType="NVarChar(50)")]
		public string NAME_AD
		{
			get
			{
				return this._NAME_AD;
			}
			set
			{
				if ((this._NAME_AD != value))
				{
					this.OnNAME_ADChanging(value);
					this.SendPropertyChanging();
					this._NAME_AD = value;
					this.SendPropertyChanged("NAME_AD");
					this.OnNAME_ADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_US", DbType="NVarChar(50)")]
		public string ACCOUNT_US
		{
			get
			{
				return this._ACCOUNT_US;
			}
			set
			{
				if ((this._ACCOUNT_US != value))
				{
					this.OnACCOUNT_USChanging(value);
					this.SendPropertyChanging();
					this._ACCOUNT_US = value;
					this.SendPropertyChanged("ACCOUNT_US");
					this.OnACCOUNT_USChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_CN", DbType="NVarChar(50)")]
		public string ACCOUNT_CN
		{
			get
			{
				return this._ACCOUNT_CN;
			}
			set
			{
				if ((this._ACCOUNT_CN != value))
				{
					this.OnACCOUNT_CNChanging(value);
					this.SendPropertyChanging();
					this._ACCOUNT_CN = value;
					this.SendPropertyChanged("ACCOUNT_CN");
					this.OnACCOUNT_CNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NATION", DbType="NVarChar(50)")]
		public string NATION
		{
			get
			{
				return this._NATION;
			}
			set
			{
				if ((this._NATION != value))
				{
					this.OnNATIONChanging(value);
					this.SendPropertyChanging();
					this._NATION = value;
					this.SendPropertyChanged("NATION");
					this.OnNATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHI_ID", DbType="NVarChar(50)")]
		public string NHI_ID
		{
			get
			{
				return this._NHI_ID;
			}
			set
			{
				if ((this._NHI_ID != value))
				{
					this.OnNHI_IDChanging(value);
					this.SendPropertyChanging();
					this._NHI_ID = value;
					this.SendPropertyChanged("NHI_ID");
					this.OnNHI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentNobr1", DbType="NVarChar(50)")]
		public string AgentNobr1
		{
			get
			{
				return this._AgentNobr1;
			}
			set
			{
				if ((this._AgentNobr1 != value))
				{
					this.OnAgentNobr1Changing(value);
					this.SendPropertyChanging();
					this._AgentNobr1 = value;
					this.SendPropertyChanged("AgentNobr1");
					this.OnAgentNobr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentNobr2", DbType="NVarChar(50)")]
		public string AgentNobr2
		{
			get
			{
				return this._AgentNobr2;
			}
			set
			{
				if ((this._AgentNobr2 != value))
				{
					this.OnAgentNobr2Changing(value);
					this.SendPropertyChanging();
					this._AgentNobr2 = value;
					this.SendPropertyChanged("AgentNobr2");
					this.OnAgentNobr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CandidatesWays", DbType="NVarChar(50)")]
		public string CandidatesWays
		{
			get
			{
				return this._CandidatesWays;
			}
			set
			{
				if ((this._CandidatesWays != value))
				{
					this.OnCandidatesWaysChanging(value);
					this.SendPropertyChanging();
					this._CandidatesWays = value;
					this.SendPropertyChanged("CandidatesWays");
					this.OnCandidatesWaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> YearDate
		{
			get
			{
				return this._YearDate;
			}
			set
			{
				if ((this._YearDate != value))
				{
					this.OnYearDateChanging(value);
					this.SendPropertyChanging();
					this._YearDate = value;
					this.SendPropertyChanged("YearDate");
					this.OnYearDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
